name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Utilisation de v3 (plus récent)

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Modifie si nécessaire
          cache: 'poetry'

      - name: Install Poetry (officiel)
        uses: abatilo/actions-poetry@v2

      - name: Check Poetry installation
        run: poetry --version  # Devrait fonctionner correctement

      - name: Install dependencies
        run: poetry install
